name: Build and Release APK

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
    
    - name: Get dependencies
      run: |
        cd squadup/frontend/squadup_app
        flutter pub get
    
    - name: Build APK
      run: |
        cd squadup/frontend/squadup_app
        flutter build apk --release
    
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: squadup-release-apk
        path: squadup/frontend/squadup_app/build/app/outputs/flutter-apk/app-release.apk
    
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: squadup/frontend/squadup_app/build/app/outputs/flutter-apk/app-release.apk
        body: |
          ## 📱 SquadUp Mobile App - ${{ github.ref_name }}
          
          ### 📥 Download
          Baixe o arquivo APK abaixo e instale no seu dispositivo Android.
          
          ### 📋 Como instalar:
          1. Baixe o arquivo `app-release.apk`
          2. No seu Android, vá em Configurações > Segurança
          3. Habilite "Fontes desconhecidas" ou "Instalar apps desconhecidas"
          4. Abra o arquivo APK baixado
          5. Siga as instruções de instalação
          
          ### ✨ Novidades nesta versão:
          - Melhorias de performance
          - Correções de bugs
          - Interface otimizada
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}